git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git submodule update --init --recursive
./autogen.sh
. /home/zhaibin18/arm_home/rc.source
CPPFLAGS="-I/home/zhaibin18/arm_home/libev/include -I/home/zhaibin18/arm_home/libudns/include"  LDFLAGS="-L/home/zhaibin18/arm_home/libudns/lib -L/home/zhaibin18/arm_home/libev/lib" ./configure --disable-documentation --disable-ssp --with-pcre=/home/zhaibin18/arm_home/libpcre_840 --with-mbedtls=/home/zhaibin18/arm_home/mbedtls_240 --host=arm-linux --with-sodium-include=/home/zhaibin18/arm_home/libsodium_1011/include --with-sodium-lib=/home/zhaibin18/arm_home/libsodium_1011/lib
make
cd shadowsocks-libev/src
arm-linux-gcc -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libbloom -I../libipset/include -I../libcork/include -DMODULE_LOCAL -g -O2 -I/home/zhaibin18/arm_home/libpcre_840/include -DPCRE_STATIC -I/home/zhaibin18/arm_home/mbedtls_240/include -I/home/zhaibin18/arm_home/libsodium_1011/include -pthread -o ss-local ss_local-utils.o ss_local-jconf.o ss_local-json.o ss_local-udprelay.o ss_local-cache.o ss_local-acl.o ss_local-netutils.o ss_local-local.o ss_local-crypto.o ss_local-aead.o ss_local-stream.o ss_local-ppbloom.o ss_local-base64.o ss_local-plugin.o ss_local-http.o ss_local-tls.o ss_local-rule.o  -L/home/zhaibin18/arm_home/libudns/lib -L/home/zhaibin18/arm_home/libev/lib -L/home/zhaibin18/arm_home/libpcre_840/lib -L/home/zhaibin18/arm_home/mbedtls_240/lib -L/home/zhaibin18/arm_home/libsodium_1011/lib ../libbloom/.libs/libbloom.a ../libipset/.libs/libipset.a ../libcork/.libs/libcork.a -lm /home/zhaibin18/arm_home/libev/lib/libev.a /home/zhaibin18/arm_home/libudns/lib/libudns.a /home/zhaibin18/arm_home/libsodium_1011/lib/libsodium.a -lmbedcrypto /home/zhaibin18/arm_home/libpcre_840/lib/libpcre.a -pthread -static
arm-linux-gcc -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libbloom -I../libipset/include -I../libcork/include -DMODULE_REMOTE -g -O2 -I/home/zhaibin18/arm_home/libpcre_840/include -DPCRE_STATIC -I/home/zhaibin18/arm_home/mbedtls_240/include -I/home/zhaibin18/arm_home/libsodium_1011/include -pthread -o ss-server ss_server-utils.o ss_server-netutils.o ss_server-jconf.o ss_server-json.o ss_server-udprelay.o ss_server-cache.o ss_server-acl.o ss_server-resolv.o ss_server-server.o ss_server-crypto.o ss_server-aead.o ss_server-stream.o ss_server-ppbloom.o ss_server-base64.o ss_server-plugin.o ss_server-http.o ss_server-tls.o ss_server-rule.o  -L/home/zhaibin18/arm_home/libudns/lib -L/home/zhaibin18/arm_home/libev/lib -L/home/zhaibin18/arm_home/libpcre_840/lib -L/home/zhaibin18/arm_home/mbedtls_240/lib -L/home/zhaibin18/arm_home/libsodium_1011/lib ../libbloom/.libs/libbloom.a ../libipset/.libs/libipset.a ../libcork/.libs/libcork.a -lm /home/zhaibin18/arm_home/libev/lib/libev.a /home/zhaibin18/arm_home/libudns/lib/libudns.a /home/zhaibin18/arm_home/libsodium_1011/lib/libsodium.a -lmbedcrypto /home/zhaibin18/arm_home/libpcre_840/lib/libpcre.a -pthread -static
arm-linux-gcc -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libbloom -I../libipset/include -I../libcork/include -DMODULE_REDIR -g -O2 -I/home/zhaibin18/arm_home/libpcre_840/include -DPCRE_STATIC -I/home/zhaibin18/arm_home/mbedtls_240/include -I/home/zhaibin18/arm_home/libsodium_1011/include -pthread -o ss-redir ss_redir-utils.o ss_redir-jconf.o ss_redir-json.o ss_redir-netutils.o ss_redir-cache.o ss_redir-udprelay.o ss_redir-redir.o ss_redir-crypto.o ss_redir-aead.o ss_redir-stream.o ss_redir-ppbloom.o ss_redir-base64.o ss_redir-plugin.o ss_redir-http.o ss_redir-tls.o ss_redir-rule.o  -L/home/zhaibin18/arm_home/libudns/lib -L/home/zhaibin18/arm_home/libev/lib -L/home/zhaibin18/arm_home/libpcre_840/lib -L/home/zhaibin18/arm_home/mbedtls_240/lib -L/home/zhaibin18/arm_home/libsodium_1011/lib ../libbloom/.libs/libbloom.a ../libipset/.libs/libipset.a ../libcork/.libs/libcork.a -lm /home/zhaibin18/arm_home/libev/lib/libev.a /home/zhaibin18/arm_home/libudns/lib/libudns.a /home/zhaibin18/arm_home/libsodium_1011/lib/libsodium.a -lmbedcrypto /home/zhaibin18/arm_home/libpcre_840/lib/libpcre.a -pthread -static

arm-linux-gcc -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libbloom -I../libipset/include -I../libcork/include -DMODULE_TUNNEL -g -O2 -I/home/zhaibin18/arm_home/libpcre_840/include -DPCRE_STATIC -I/home/zhaibin18/arm_home/mbedtls_240/include -I/home/zhaibin18/arm_home/libsodium_1011/include -pthread -o ss-tunnel ss_tunnel-utils.o ss_tunnel-jconf.o ss_tunnel-json.o ss_tunnel-udprelay.o ss_tunnel-cache.o ss_tunnel-netutils.o ss_tunnel-tunnel.o ss_tunnel-crypto.o ss_tunnel-aead.o ss_tunnel-stream.o ss_tunnel-ppbloom.o ss_tunnel-base64.o ss_tunnel-plugin.o  -L/home/zhaibin18/arm_home/libudns/lib -L/home/zhaibin18/arm_home/libev/lib -L/home/zhaibin18/arm_home/libpcre_840/lib -L/home/zhaibin18/arm_home/mbedtls_240/lib -L/home/zhaibin18/arm_home/libsodium_1011/lib ../libbloom/.libs/libbloom.a ../libipset/.libs/libipset.a ../libcork/.libs/libcork.a -lm /home/zhaibin18/arm_home/libev/lib/libev.a /home/zhaibin18/arm_home/libudns/lib/libudns.a /home/zhaibin18/arm_home/libsodium_1011/lib/libsodium.a -lmbedcrypto /home/zhaibin18/arm_home/libpcre_840/lib/libpcre.a -pthread -static 
